### ISSUE TITLE
DisplayPort via Type-C hot plug does not work.

### ISSUE THREAD

**Issue by tofuliang** [bavariancake/XPS9570-macOS#21] opened 2019-05-29 15:00 UTC
I have Dell D6000 Dock station, Dell P2414H, HKC T4000.
Dell P2414H connect to D6000 with DisplayPort, HKC T4000 connect to D6000 with HDMI.
And D6000 connect to XPS 9570 with Type-C port.
When attached D6000 prior to boot, all monitor work fine.
![attached D6000 prior to boot](https://user-images.githubusercontent.com/1814685/58566462-4a36f680-8263-11e9-9672-85c1e0e5358c.png)

Unplug and plug D6000, only HDMI monitor and build in monitor work.

![hotpluged](https://user-images.githubusercontent.com/1814685/58566705-aa2d9d00-8263-11e9-8f77-76586f132d83.png)

But when I look it up in System Information, Dell P2414H never show up.
When D6000 connect to XPS 9570 with Type-A port, using DisplayLink, all monitor work fine.

**Comment by bavariancake** [comment] 2019-06-01 18:15
Is the first monitor with 3008x1692 resolution the internal one?

The first screenshot only shows two monitors under SysInfo->Graphics/Displays. Is the Dell P2414H connected via DisplayLink in that case? Of course DisplayLink looks like a virtual graphics card and bypasses Intel graphics, so I can see why that would work.

What happens when you uninstall DisplayLink drivers/software and only connect the Dell P2414H to the D6000 via USB C? Does hotplugging work? What about the other DP output on the D6000?

This hub is doing a lot of different things, so it's hard to say what the problem is without more info.

**Comment by bavariancake** [comment] 2020-02-06 12:06
I'm currently using DisplayPort via the USB type-C connector, and it works as expected (4k, 60Hz). Hot plugging works also. Closing issue as resolved.

**Closed by bavariancake** 2020-02-06 12:06 UTC
